include:
  - board: nice_nano_v2
    shield: dasbob_left
    artifact-name: dasbob_left
  - board: nice_nano_v2
    shield: dasbob_right
    artifact-name: dasbob_right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: dasbob_reset
  - board: nice_nano_v2
    shield: tester_pro_micro
    artifact-name: dasbob_tester
